INSERT INTO candidatedirectory (
    event_id,
    job_position_id,
    recruiter_alert,
    first_name,
    last_name,
    email,
    persona_id,
    role,
    screening_mode_id,
    dob,
    gender_id,
    marital_status_id,
    contact_no_primary,
    contact_no_alternate,
    referred_by_id,
    referred_by_other,
    address_line,
    city_id,
    pincode,
    experience_level_id,
    education_level_id,
    education_qualification_id,
    education_specialization_id,
    education_specialization_other,
    education_institution_id,
    education_institution_other,
    source_id,
    source_type_id,
    years_of_experience,
    current_employer,
    current_designation,
    current_monthly_salary,
    expected_monthly_salary,
    notice_period,
    reason_for_change_id,
    photo_path,
    resume_path,
    login_time,
    logout_time,
    ip_address,
    geo_location,
    created_date,
    created_by,
    modified_date,
    modified_by,
    status
)
VALUES (
    1, 
    1,  
    'Recruiter Alert Message',
    'John',
    'Wick',
    'john.wick@example.com',
    1, 
    1, 
    2,  
    '2000-01-01',  
    1, 
    1, 
    123456790,
    0987654321,
    2, 
    'Mark William',
    '123 Main Street',
    2, 
    123456,
    2, 
    2, 
    2, 
    1,  
    'Bio Medical',
    1,  
    'ZYX University',
    2,  
    1, 
    1.2,
    'ABC Company',
    'Software Developer',
    10000,
    12000,
    '30 days',
    1,  
    '\files\assest\photos\John.jpg',
    '\files\assest\resume\John.pdf',
    '2023-08-22 12:00:00',  
    '2023-08-22 18:00:00',  
    '192.168.1.1',
    'Madurai',
    '2023-08-22 12:00:00',  
    1, 
    '2023-08-22 12:00:00',  
    1, 
    1  
);