# Generated by Django 4.2.2 on 2023-09-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='BlogUserComments',
            table='BlogUserComments',
        ),
    ]
