# Generated by Django 4.2.2 on 2023-09-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_usercomments_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUsersLikes',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_like', models.BooleanField(blank=True, db_column='is_Like', null=True)),
            ],
            options={
                'db_table': 'blog_users_likes',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='blogusercomments',
            table='blog_user_comments',
        ),
    ]
