# Generated by Django 4.2.2 on 2023-09-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_token'),
        ('blog_app', '0004_alter_bloglists_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogusercomments',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bloguserslikes',
            name='is_like',
        ),
        migrations.AddField(
            model_name='bloglists',
            name='isDelete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bloglists',
            name='isUpdate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bloglists',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.blogusers'),
        ),
        migrations.AddField(
            model_name='blogusercomments',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_app.bloglists'),
        ),
        migrations.AddField(
            model_name='blogusercomments',
            name='isUpdate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='blogusercomments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.blogusers'),
        ),
        migrations.AddField(
            model_name='bloguserslikes',
            name='isLike',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloguserslikes',
            name='like_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog_app.bloglists'),
        ),
        migrations.AddField(
            model_name='bloguserslikes',
            name='like_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.blogusers'),
        ),
    ]
