# Generated by Django 4.2.2 on 2023-09-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_blogusers_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
